name: pypath
channels:
- conda-forge
dependencies:
- conda-forge::python=3.8.3
- conda-forge::pandas=1.0.4
- conda-forge::numpy=1.18.4
- conda-forge::scipy=1.4.1
- conda-forge::biopython=1.76
- conda-forge::tqdm=4.38.0
